changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
    authors:
      - dependabot[bot]

  categories:
    - title: Features
      labels:
        - enhancement
        - feature

    - title: Fixes
      labels:
        - bug
        - fix

    - title: Packaging and maintenance
      labels:
        - packaging
        - maintenance
        - "*"
