[package]
name = "niripip-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[[bin]]
name = "niripip-ui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
niripip-core = { path = "../niripip-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml_edit.workspace = true
