#!/usr/bin/env bash
set -euo pipefail

OUT="${1:-niripip-debug-$(date +%Y%m%d-%H%M%S).txt}"
exec 3>"$OUT"

section() { printf '\n===== %s =====\n' "$1" >&3; }

section "versions"
printf 'date: %s\n' "$(date --iso-8601=seconds 2>/dev/null || date)" >&3
printf 'niri: ' >&3; niri --version >&3 2>&1 || true
printf 'niripip: ' >&3; niripip --version >&3 2>&1 || true

section "safe session environment"
for key in XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY DISPLAY XDG_RUNTIME_DIR NIRI_SOCKET; do
    value="${!key-<unset>}"
    printf '%s=%s\n' "$key" "$value" >&3
done

section "sanitized Niri windows"
if command -v niri >/dev/null 2>&1; then
    if command -v jq >/dev/null 2>&1; then
        niri msg --json windows 2>/dev/null | jq '[.[] | {
            id,
            title: (if .title == null then null else "<redacted>" end),
            app_id,
            pid: (if .pid == null then null else "<present>" end),
            workspace_id,
            is_focused,
            is_floating,
            is_urgent,
            layout
        }]' >&3 || true
    else
        printf 'jq is unavailable; window state omitted instead of writing unredacted titles.\n' >&3
    fi
fi

section "sanitized Niri workspaces"
if command -v niri >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    niri msg --json workspaces 2>/dev/null | jq '[.[] | {
        id, idx, name: (if .name == null then null else "<redacted>" end), output,
        is_urgent, is_active, is_focused, active_window_id
    }]' >&3 || true
fi

section "sanitized outputs"
if command -v niri >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    niri msg --json outputs 2>/dev/null | jq 'to_entries | map({
        name: .key,
        logical: .value.logical,
        current_mode: .value.current_mode
    })' >&3 || true
fi

section "daemon status"
niripip --json status >&3 2>&1 || true

section "systemd service"
systemctl --user status niripip.service --no-pager >&3 2>&1 || true

section "recent journal"
journalctl --user -u niripip.service -b --no-pager -n 120 >&3 2>&1 || true


# Runtime rules are generated by niri-pip and contain only the PiP match/opacity policy.
RUNTIME_KDL="${XDG_CONFIG_HOME:-$HOME/.config}/niri/niri-pip-runtime.kdl"
if [[ -f "$RUNTIME_KDL" ]]; then
    section "niri-pip runtime rule"
    cat "$RUNTIME_KDL" >&3
fi

exec 3>&-
printf 'Wrote %s\nReview it before sharing. The script intentionally does not collect browser data, cookies, tokens, SSH keys, or arbitrary environment variables.\n' "$OUT"
