#!/usr/bin/env bash
set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
NIRI_DIR="$CONFIG_HOME/niri"
INIR_EXTRA="$NIRI_DIR/config.d/90-user-extra.kdl"
MAIN_CONFIG="$NIRI_DIR/config.kdl"
RUNTIME_FILE="$NIRI_DIR/niri-pip-runtime.kdl"

if [[ -f "$INIR_EXTRA" ]]; then
  TARGET="$INIR_EXTRA"
elif [[ -f "$MAIN_CONFIG" ]]; then
  TARGET="$MAIN_CONFIG"
else
  echo "error: could not find $INIR_EXTRA or $MAIN_CONFIG" >&2
  exit 1
fi

mkdir -p "$NIRI_DIR"
touch "$TARGET"
BACKUP="$TARGET.bak.niripip.$(date +%Y%m%d-%H%M%S)"
cp -a "$TARGET" "$BACKUP"

python - "$TARGET" "$RUNTIME_FILE" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
runtime = sys.argv[2]
runtime_kdl = runtime.replace("\\", "\\\\").replace('"', '\\"')
text = path.read_text()

blocks = [
    ("// >>> niri-pip opacity override >>>", "// <<< niri-pip opacity override <<<"),
    ("// >>> niri-pip runtime include >>>", "// <<< niri-pip runtime include <<<"),
]
for start, end in blocks:
    while start in text and end in text:
        before, rest = text.split(start, 1)
        _, after = rest.split(end, 1)
        text = before.rstrip() + "\n" + after.lstrip("\n")

block = f'''
// >>> niri-pip runtime include >>>
// niri-pip runtime rules
include optional=true "{runtime_kdl}"
// <<< niri-pip runtime include <<<
'''
tmp = path.with_name(path.name + ".niripip.tmp")
tmp.write_text(text.rstrip() + "\n\n" + block.lstrip())
tmp.replace(path)
PY

if [[ ! -f "$RUNTIME_FILE" ]]; then
  cat > "$RUNTIME_FILE" <<'KDL'
// Generated by niri-pip. Do not edit while niripipd is running.
window-rule {
    match title=r#"(?i)^picture(?:[ -]?in[ -]?)picture$"#
    opacity 1.00
}
KDL
  chmod 600 "$RUNTIME_FILE"
fi

if command -v niri >/dev/null 2>&1 && [[ -n "${NIRI_SOCKET:-}" ]]; then
  if ! niri validate; then
    echo "error: Niri rejected the integration; restoring $BACKUP" >&2
    cp -a "$BACKUP" "$TARGET"
    niri validate || true
    exit 1
  fi
fi

echo "niri-pip Niri integration installed"
echo "  include: $TARGET"
echo "  runtime: $RUNTIME_FILE"
echo "  backup:  $BACKUP"
